// Supabase Configuration for Omni-jimmer
// Replace with your actual Supabase project values

// This file will be generated by GitHub Actions with real secrets
// Keep this as template/fallback for local development

const supabaseConfig = {
  // Placeholder - GitHub Actions will inject real values
  url: 'GITHUB_ACTIONS_WILL_REPLACE_THIS',
  anonKey: 'GITHUB_ACTIONS_WILL_REPLACE_THIS',
  
  // Edge Function URLs (will be generated from URL)
  functions: {
    openai: 'GITHUB_ACTIONS_WILL_REPLACE_THIS/functions/v1/openai-proxy',
    replicate: 'GITHUB_ACTIONS_WILL_REPLACE_THIS/functions/v1/replicate-proxy'
  }
};

// Export for use in main app
window.supabaseConfig = supabaseConfig;
